### ISSUE TITLE
Support fixing AMP links.

### ISSUE THREAD

**Issue by luciph0r** [TrianguloY/UrlChecker#145] opened 2022-11-21 22:28 UTC
**Is your feature request related to a problem? Please describe.**
Support fixing AMP links. Google amp directs traffic through their servers, would be good if detected amp links were fixable.

**Describe the solution you'd like**
A module that detects and offers to fix amp links. 

**Describe alternatives you've considered**
Have to depend on browser extensions, which aren't supported on Android versions of popular browsers.

**Comment by PabloOQ** [comment] 2022-11-22 10:29
Duplicate of #13 , I'm closing this issue.
Have you tried using the URL Cleaner module? It should clean AMP links. If it does not, please post the link or one with the same structure if you can.

**Closed by PabloOQ** 2022-11-22 10:29 UTC

**Comment by luciph0r** [comment] 2022-11-22 13:17
It doesn't work with amp, which is why I raised the issue in the first place.
