### ISSUE TITLE
Originating browser does not appear in the Open with list

### ISSUE THREAD

**Issue by backtabber** [TrianguloY/UrlChecker#274] opened 2023-09-01 20:37 UTC
### Steps to reproduce

When sharing a link with URLChecker from a browser, that same browser does not appear on the Open with dropdown.

I consider this a bug, because it is quite feasible that someone would like to change the url with the Pattern Checker, and then open the modified url in the *same browser*.

Otherwise, thanks for this amazing, well-designed app.

### Expected behavior

The originating browser should appear on the open with list

### Actual behavior

It doesn't

### URLCheck version

2.12

### Android version

Android 9

### Android Custom/Specific ROM or Device

stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-09-01 21:24
Exactly. Thanks Murilogs.

You can see the rationale for why this feature was implemented here: #92
It will probably change in the future though, you are not the first to report this.

Closed as duplicate of #134

**Closed** 2023-09-01 21:24 UTC
Labels: bug

**Comment by backtabber** [comment] 2023-09-01 21:31
Thanks.
