### ISSUE TITLE
unable open a link in app which it shared from

### ISSUE THREAD

**Issue by rhjdvsgsgks** [TrianguloY/UrlChecker#236] opened 2023-05-17 14:06 UTC
### Steps to reproduce

1. share a url from browser to urlchecker
2. it says "No apps" and unable to open the url in browser

### Expected behavior

able to open url in browser even if it shared from browser

### Actual behavior

urlchecker says "No apps" and unable to open the url in browser

### URLCheck version

2.11

### Android version

11

### Android Custom/Specific ROM or Device

lineage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-05-17 14:12
Duplicate of #134

And yes, you can disable that:
Modules > Open&share > turn off "hide the source app"

You can see the rationale for why this feature was implemented here: #92

**Closed** 2023-05-17 14:13 UTC
Labels: bug

**Comment by TrianguloY** [comment] 2023-05-17 14:49
Don't worry.
I agree the setting should be renamed or explained better, but I haven't find a better alternative yet. Your suggestion is interesting but I'm not sure if it l will help, for me its more confusing :/
