### ISSUE TITLE
Option to Whitelist trusted sites

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [TrianguloY/UrlChecker#392] opened 2024-10-25 17:11 UTC
### Describe a related problem (optional)

It's annoying Whenever we click some websites which we trust like some GitHub repository or something like which we know we don't neet to check but still have to click multiple times just to get past urlChecker.

### Describe your suggested feature

It would be great if we can just white list or add some sites to a trusted sites list, so whenever we click such a website urlChecker automatically opens it in the browser without needing us to click the open button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment] 2024-10-25 22:14
Thanks for the suggestion! We already have this on the radar. Triangulo is currently working on an automation feature, and if I'm not mistaken this is included there, you can read more on #383.

Closing as duplicate of #192

**Closed by PabloOQ** 2024-10-25 22:14 UTC
Labels: enhancement

**Comment by TrianguloY** [comment] 2024-10-26 10:04
That's right.

The next version, which is almost ready, will include a basic yet powerful automation feature that will allow you to "automatically press open" for any urls you want (that match a regex). This first version will open the first available app in the list (you will not be able to specify exactly which app to open) but that will probably come at a later version.
