### ISSUE TITLE
Incognito Mode don't work

### ISSUE THREAD

**Issue by saltsoftdrink** [TrianguloY/UrlChecker#319] opened 2024-02-19 12:53 UTC
### Steps to reproduce

Open Brave in Incognito Mode

### Expected behavior

It should open it in incognito mode brave  browser 

### Actual behavior

Instead of opening in incognito it opens in normal mode brave  browser 

### URLCheck version

2.13.1

### Android version

Android 14

### Android Custom/Specific ROM or Device

Color OS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment] 2024-02-19 13:39
Not a bug, this is not implemented yet, you can find the discussion on #115.

The app currently doesn't support opening incognito in any browser that is not a fork of firefox (fenix). Chromium browsers (such as brave) ignore the URL when we request it to be opened in incognito. I want, at some point, to add an accesibility service that injects the URL in the search bar, but because it can technically break at any point and also accesibility services are restricted, I am first developing an alternative that borrows the clipboard for a moment, then the user should paste the URL into the search bar.

Closing as duplicate.

**Closed by PabloOQ** 2024-02-19 13:39 UTC
Labels: bug
