### ISSUE TITLE
inline url cleaning

### ISSUE THREAD

**Issue by rhjdvsgsgks** [TrianguloY/UrlChecker#256] opened 2023-07-06 08:03 UTC
### Describe a related problem (optional)

when i want to clean a url (or process a string by regex) in a text box. for now i need to select the string. share to urlchecker. apply custom regex rule. copy the cleaned string. select the original string again. paste to replace it. there are some step can be simplified

### Describe your suggested feature

inline text replacement.
when url cleaning interface showed by opening from text operation. add a button to replace original selected text with processed one

### Other details

a app have thw feature i said: https://github.com/JanmanX/EncryptTextApp

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment] 2023-07-06 09:10
Closing as duplicate of #191.

**Closed by PabloOQ** 2023-07-06 09:10 UTC
Labels: enhancement
