### ISSUE TITLE
Firefox sometimes not showing in the list of browsers 

### ISSUE THREAD

**Issue by beeb** [TrianguloY/UrlChecker#277] opened 2023-09-20 05:41 UTC
### Steps to reproduce

I have installed the Voyager PWA through Firefox to browse Lemmy. vygr.app/

When clicking a link in the app (which is Firefox), a prompt asks me if I want to open the link in another app (that's a bit annoying) and it then opens in URLCheck. 

In the pop-up, I don't see an option to open the link with Firefox. All my other browsers show up (chrome, brave, kiwi) but not Firefox.

However, if I click on the test link in the URLCheck main window, I do see Firefox in the list. 

### Expected behavior

Firefox should be an option 

### Actual behavior

Firefox is not shown

### URLCheck version

2.12

### Android version

13

### Android Custom/Specific ROM or Device

OxygenOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-09-20 06:18
Duplicate of #134

And yes, you can disable that:
Modules > Open&share > turn off "hide the source app"

You can see the rationale for why this feature was implemented here: #92

<sub><sub>This is definitely an issue...I should change this asap</sub></sub>

**Closed** 2023-09-20 06:19 UTC
Labels: bug

**Comment by beeb** [comment] 2023-09-20 06:21
Oh thanks, I missed that setting somehow!
