### ISSUE TITLE
Pattern Checker: Optional groups yield "null" instead of an empty string

### ISSUE THREAD

**Issue by the-blank-x** [TrianguloY/UrlChecker#237] opened 2023-05-21 14:09 UTC
### Steps to reproduce

1. Add the following into the Pattern Checker config:
```json
[
  "Optional groups": {
    "regex": "^https:\/\/test\\.invalid\/(.+)?$",
    "excludeRegex": "^https:\/\/test\\.invalid\/exclude\/",
    "replacement": "https:\/\/test.invalid\/exclude\/$1"
  }
]
```
2. Open https://test.invalid/
3. Apply the pattern

### Expected behavior

The URL gets transformed into https://test.invalid/exclude/

### Actual behavior

The URL gets transformed into https://test.invalid/exclude/null

### URLCheck version

2.11

### Android version

Android 9

### Android Custom/Specific ROM or Device

OxygenOS 9.0.10

### Other details

I encountered this bug through this monstrosity that adds `?useskin=vector` to links for wiki.archlinux.org:
```json
[
  "Use old skin for Arch Linux Wiki": {
    "regex": "^https?:\/\/wiki\\.archlinux\\.org\/([^#?]*?)(?:\\?([^#]+))?(#.+)?$",
    "excludeRegex": "^https?:\/\/wiki.archlinux.org\/.*[?&]useskin=",
    "replacement": "https:\/\/wiki\\.archlinux\\.org\/$1?useskin=vector&$2$3",
    "automatic": true
  }
]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-05-21 14:22
Oh! Nice catch.

Optional groups are a bit dangerous because following groups index may shift, I think it may be better to replace them with mandatory catch-empty ones: (.*) instead of (.+)?

In any case, if the user do use them the module should return the empty string (I guess it's the logical think to do, it's a bit on the undefined size but I guess it makes more sense than "null").

Should be a really easy fix. Thanks!

**Comment by the-blank-x** [comment] 2023-05-21 14:37
The example I've shown uses optional groups for the sake of demonstrating the bug, but I'm not sure how to avoid them for the other pattern in Other details.

I don't think the group indexes would shift. [Regex101's Java implementation](https://regex101.com/r/RcmGOy/2) works properly with a regex of `^(a+)(b+)?(c+)$` and replacement of `a: $1\nb: $2\nc: $3`, and [Rextester](https://rextester.com/l/java_online_compiler) works properly with:
```java
class Rextester {
    private static void testString(String str) {
        String out = str.replaceAll("^^(a+)(b+)?(c+)$$", "a: $1\nb: $2\nc: $3");
        System.out.println(out);
    }

    public static void main(String args[]) {
        testString("aaabbbccc");
        System.out.println();
        testString("aaaccc");
    }
}
```

**Comment by TrianguloY** [comment] 2023-05-21 14:40
Really? Oh, I didn't know that.
Strange it returns null then...

**Comment by TrianguloY** [comment] 2023-05-21 22:01
Ok, so I have good news and bad news.

The good news is that the bug was present in the Android source code, and it was fixed on [2019](https://android-review.googlesource.com/c/platform/libcore/+/971154).

The bad news are that apparently that fix was made available on Android 11+ (maybe even android 10, it's hard to tell, definitely not Android 9). I can't reproduce it on my Android 12 device for example.

Trying to solve it from my side is quite hard, and I need to be extra careful not to add more bugs in the process. The replacement code is just [url.replaceAll(regex, replacement)](https://github.com/TrianguloY/UrlChecker/blob/1adf96e31f23b6b9f62ff16b75a46e8a93f148dd/app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java#L161), and making my own regexp matcher is impossible.
I'll try to fix it by 'patching' the matcher class, but I can't promise it'll work.

Definitely not an 'easy' task, sorry :(

**Comment by the-blank-x** [comment] 2023-05-22 08:18
Is it ok for me to take a jab at this if I had looked at Android's source code?

**Closed** 2023-06-10 11:42 UTC
Labels: bug, wontfix
