### ISSUE TITLE
Add modules for privacy respecting front ends 

### ISSUE THREAD

**Issue by rpdelaney** [TrianguloY/UrlChecker#144] opened 2022-11-19 15:22 UTC
https://github.com/digitalblossom/alternative-frontends

I'd like to be able to use this app to convert share links to privacy respecting versions for friends who don't have these apps and don't trust the sites tracking them.

**Comment by PabloOQ** [comment] 2022-11-19 15:42
This is something we already want to do #7.
At the moment the patterns checker module can be configured to mimic this feature, you can find the patterns here: https://github.com/TrianguloY/UrlChecker/wiki/Custom-patterns
If you want to read more or share your thoughts about this pattern you can do it on #122 .
Don't know if this issue should be closed, as the proposed list for alternatives is not the same as #7.

**Comment by TrianguloY** [comment] 2022-11-19 16:19
I'll close it as duplicate of #7, yes.
The main issue with these services is that they all seem to require a manually created list of instances, which can quickly become out of date and hard to maintain. It doesn't seem to be a centralized "what is the redirection of this url" service (which I understand due to the privacy oriented nature of them).
Farside seems to be the nearest thing, maybe a "farside module"...

**Closed by TrianguloY** 2022-11-19 16:19 UTC
Labels: enhancement
