### ISSUE TITLE
auto redirection of url in status code module.

### ISSUE THREAD

**Issue by nihal697** [TrianguloY/UrlChecker#177] opened 2023-02-12 16:57 UTC
### Describe your suggested feature

Is it possible to automate the redirection of url in status code module? 
![Screenshot_20230212-222506_Trebuchet_1](https://user-images.githubusercontent.com/47318989/218325179-526a6c0d-6cb7-4cf0-9d18-46007a933aeb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-02-12 17:01
Duplicate of https://github.com/TrianguloY/UrlChecker/issues/25

It's already implemented, will be available on the next version.

Closing as completed

**Closed** 2023-02-12 17:01 UTC
Labels: enhancement

**Comment by nihal697** [comment] 2023-02-12 17:02
damn that's nice, thanks a lot man, your app is revolutionary really. ♥
