### ISSUE TITLE
UrlChecker does not always show all available apps in the "Open with" menu when invoked from a browser 

### ISSUE THREAD

**Issue by luca-e075e** [TrianguloY/UrlChecker#161] opened 2022-12-24 13:26 UTC
**Describe the bug**
UrlChecker does not always show all available apps in the "Open with" menu when invoked from a browser 

**To Reproduce**
1. Install two browsers, eg Firefox and Brave
2. Open one of them, eg Firefox
3. search something on internet. eg wikipedia
4. long press on one result
5. Share with "UrlCheck"

**Current behaviour**
UrlCheck shows "Open with Brave", Firefox is not listed in the menu as a choice.
Same behaviour if Brave is used first, in this case only "Open with Firefox" is shown.

**Expected behaviour**
UrlCheck shows all available apps for the supported link

**Workaround**
on the UrlCheck "open with" screen, choose "share" and select the other browser

**System Info (please complete the following information):**
 - Device: Oppo CPH1931
 - Android OS version: 10
 - URLCheck version: 2.9 fdroid
 - Browser: Firefox and Brave

**Additional context**
sharing links to UrlCheck from a browser is useful to redirect services to their non tracking counterparts (such as twitter -> nitter), checking shot links, etc

**Comment by PabloOQ** [comment] 2022-12-24 13:37
IIRC this is on purpose, but I'm not sure. I agree it should appear, maybe an option to change this behaviour would benefit everyone, after activating this option it would make it work like it did some time ago where it listed all available apps and the default one is the "most used" one, like it currently does.

**Comment by TrianguloY** [comment] 2022-12-24 13:47
Duplicate of https://github.com/TrianguloY/UrlChecker/issues/134

And yes, you can disable that:
Modules > Open&share > turn off "hide the source app"

You can see the rationale for why this feature was implemented here: https://github.com/TrianguloY/UrlChecker/issues/92

**Closed** 2022-12-24 13:47 UTC
Labels: bug
