### ISSUE TITLE
Google Lens link opening fails 

### ISSUE THREAD

**Issue by mateoke** [TrianguloY/UrlChecker#303] opened 2023-12-21 04:02 UTC
### Steps to reproduce

Scan a QR code using Google Lens or AI camera in the default camera app
 Try to follow the link highlighted 

### Expected behavior

Offer to open the link in a browser to proceed to view link contents

### Actual behavior

Nothing happens.
If I'm in the camera app, the instruction is to click the shutter/capture button to open the link. This does nothing. 

### URLCheck version

2.1.3

### Android version

Android 13

### Android Custom/Specific ROM or Device

Oxygen OS on OnePlus 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment] 2023-12-29 12:43
The current version (2.13) has some issues with some apps due to how android manages instances, however the new version (2.13.1), which should be available in a couple days (although it is already available as a beta on play store) should hopefully fix this. If you try it and it still doesn't work please tell me.

**Comment by TrianguloY** [comment] 2024-01-08 14:07
Version 2.13.1 is (finally) available on both play store and f-droid.
It should hopefully fix the issue, and since you haven't said anything I'll assume it did.

However, if it didn't and you still have the bug, just reopen this issue and I'll take another look, no problem.

**Comment by M1xel** [comment] 2024-01-16 15:59
> Version 2.13.1 is (finally) available on both play store and f-droid. It should hopefully fix the issue, and since you haven't said anything I'll assume it did.
> 
> However, if it didn't and you still have the bug, just reopen this issue and I'll take another look, no problem.

I have just updated to 2.13.1 and tried again but it doesn't seem to work.
I haven't restarted the device if that is necessary, I have only force closed it and reopened it. 
I installed URLChecker via F-Droid 
![Screenshot_2024-01-16-16-58-24-12_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/TrianguloY/UrlChecker/assets/83142908/53f04b1c-5f17-412f-9512-992e709427b7)
Anything obvious I am missing by any chance?

**Comment by TrianguloY** [comment] 2024-01-16 16:46
Restarting should not be necessary.
Do you have the flags module enabled by any chance? Try disabling it if not.

I'm going to reopen the issue and will try to reproduce it myself.

**Comment by M1xel** [comment] 2024-01-16 17:42
If you mean the flags editor then I don't have that enabled.
To iterate google lens detects the QR code successfully and displays it correctly, but you cannot click the element to open the link at all.
My modules should be default or near the default at least I don't remember changing it that much if at all.
Below are my enabled modules: 
![Screenshot_2024-01-16-18-35-49-12_21561dfd7cdb810023cdb17e8b11e256](https://github.com/TrianguloY/UrlChecker/assets/83142908/cb67c069-e7df-4a69-810f-e56be7d7d740)
![Screenshot_2024-01-16-18-35-58-29_21561dfd7cdb810023cdb17e8b11e256](https://github.com/TrianguloY/UrlChecker/assets/83142908/ff3b1c13-e8b8-446c-9574-5f4ce98aae95)
![IMG_20240116_183715 (1)](https://github.com/TrianguloY/UrlChecker/assets/83142908/25e99e67-395b-4fdd-a7b7-f4050ca7949a)
Hope this could help you identify the problem, if you need further details i am very happy to provide them.
I am also using a OnePlus 8 Pro if that matters

**Comment by TrianguloY** [comment] 2024-01-16 17:50
I've checked lens on my device and can confirm it does not work.
The link is not opened, so the issue is with the intent sent _to the app_, not from the app (sorry, I misunderstood your first comment).

I'll check to see if it can be fixed easily. Unfortunately I can't say when a fix will be released, sorry.

**Comment by M1xel** [comment] 2024-01-16 17:53
No worries I am absolutely glad that you could reproduce it :)
And no need to pressure things, I will love the app no matter what even if it means I don't have a working QR code :D
I specifically want to thank you as a developer!

**Closed** 2024-03-16 13:02 UTC
Labels: bug
