### ISSUE TITLE
Add copy url button

### ISSUE THREAD

**Issue by User1l0** [TrianguloY/UrlChecker#98] opened 2022-09-16 22:25 UTC

**Comment by TrianguloY** [comment] 2022-09-17 06:12
You can long press the share button, which does copy the url to the clipboard (I think that's what you asked for, isn't it?)

I remember this was discussed somewhere, to separate the open and share functions which will make more space to add extra buttons. I don't see an issue with it so I'll keep this.

**Comment by Ilithy** [comment] 2022-09-17 06:28
> I remember this was discussed somewhere, to separate the open and share functions which will make more space to add extra buttons.

Yup, on #37 and #47

**Comment by TrianguloY** [comment] 2023-03-12 19:07
> issue can be closed

Hmm, the issue is not yet implemented. Why do you suggest to close it?

**Comment by TrianguloY** [comment] 2023-03-13 07:19
Correct, I explained it on my comment.
However I decided to keep the issue open because the idea is to add a dedicated separate button. Adding functionality to a button long press allows for compact UIs, but it's hard for discoverability.

**Comment by TrianguloY** [comment] 2023-03-13 10:27
I've never said I was going to remove that functionality, but rather add a separate button. I'm also glad to hear you like it, I added it for myself and without any way to track the users usage it's hard to know if a functionality is used or not.

In any case it's still something to think about, that won't probably change in the near future.

**Closed** 2023-05-27 10:08 UTC
Labels: enhancement
